---
title: "02_test_lobit_model"
author: "Miles Williams"
date: "June 11, 2019"
output: html_document
---

```{r setup 2, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message = F,
                      warning = F)
```

In this file, I do a simple comparison between Tobit and lobit models using simulated data.

```{r load libraries 2}
library(tidyverse)
library(AER)
library(lmtest)
library(dotwhisker)
# Render previous dependencies
rmarkdown::render("01_lobit_likelihood_function.Rmd")
```

### 1. Generate data:
```{r fake data}
N = 300 # num. of observations
K = 3   # num. of covariates
apply(
  matrix(0,ncol=K,nrow=N),
  2,
  function(x) rnorm(n=N)
) -> X # covariates
c('x1','x2','x3') -> colnames(X) # variable names
c(1,.3,-2,3) -> b # parameter values for linear predictor
cbind(1,X)%*%b + rnorm(n=N) -> y # latent outcome
y*(y>0) -> y_cen # censored outcome

# Put fake data in data frame:
data.frame(
  y,
  y_cen,
  obs_n = 1:length(y)
) %>%
  left_join(y=data.frame(X) %>%
              mutate(obs_n=1:n())) -> 
  df # data frame
```

### 2. Estimate Tobit and lobit models
```{r estimate models}
# Estimate Tobit model
tobit(
  y_cen ~ x1 + x2 + x3,
  data = df
) -> 
  tobit_model

# Estimate lobit model
with(df,lobit(
    y = y_cen,
    X = cbind(x1,x2,x3)
  )) ->
  lobit_model

# Estimate ols model for comparison
lm(
  y_cen ~ x1 + x2 + x3,
  data = df
) -> 
  ols_model

# EStimate latent ols model for comparison
lm(
  y ~ x1 + x2 + x3,
  data = df
) -> 
  censored_model
```


### 3. Compare model estimates
```{r make coefficient plot}
rbind(
  broom::tidy(coeftest(tobit_model)) %>%
    mutate(model="Tobit"),
  lobit_model$sum %>%
    mutate(model="Lobit"),
  broom::tidy(ols_model) %>%
    mutate(model="OLS"),
  broom::tidy(censored_model) %>%
    mutate(model="Latent OLS")
) %>%
  dwplot(show_intercept = T) +
  geom_vline(xintercept=0) +
  theme_classic() +
  scale_x_continuous(
    breaks=seq(-2.5,3,0.5)
  ) + 
  labs(
    x = "Coefficient Estimate\n(95% CIs shown)",
    color = ""
  ) +
  theme(text=element_text(family='serif')) +
  ggsave('coef_plot.pdf',
         units = 'in',
         height = 3,
         width = 6)
```

### Compare model fit with actual latent outcome:
```{r make smooth plot}
df %>%
  mutate(
    Tobit = fitted(tobit_model),
    Lobit = lobit_model$fit,
    OLS = fitted(ols_model),
    Latent = fitted(censored_model)
  ) %>%
  gather('Tobit','Lobit','OLS','Latent',
    key = "Model",
    value = "Prediction"
  ) %>%
  ggplot() +
  aes(
    x = Prediction,
    y = y,
    color = Model
  ) + 
  geom_smooth(
    alpha = .05,
    se = F,
    size = 1.5
  ) +
  labs(
    y = "Latent Outcome"
  ) +
  theme_classic() +
  theme(text=element_text(family='serif')) +
  ggsave('smooth_plot.pdf',
         units = 'in',
         height = 3,
         width = 6)
```

